# Spring properties
spring:
  application:
     name: web-ui

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

server:
  port: 8080   # HTTP (Tomcat) port
