spring:
  application:
    name: web
  thymeleaf:
    cache: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1337/eureka/
server:
  port: 8080
logging:
  level:
    me.klez.webui.clients: DEBUG
