spring:
  application:
    name: templates
  data:
    host: localhost
    port: 6379
    redis:
      password: templates-provider
      usePool: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1337/eureka/
server:
  port: 1339
